# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('0', 'DNI'), ('1', 'Pasaporte'), ('2', 'Carnet de Extranjeria'), ('3', 'Carnet Universitario')], max_length=1)),
                ('value', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Documento',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('born_date', models.DateField(blank=True, null=True)),
                ('cellphone', models.CharField(blank=True, max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('last_name_father', models.CharField(max_length=100)),
                ('last_name_mother', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(blank=True, choices=[('0', 'Femenino'), ('1', 'Masculino')], max_length=1)),
            ],
            options={
                'verbose_name': 'Persona',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
    ]
